### ISSUE TITLE
extension experienced internal errorError: spawnSync C:\windows\system32\cmd.exe ENOENT

### ISSUE THREAD

**Issue by hrai** [jonsmithers/vscode-open-in-vim#2]
I get this error when trying to open a file in gVim on windows.

![image](https://user-images.githubusercontent.com/4055444/44443639-1e277e80-a61c-11e8-94b5-3fe71cbcdc7c.png)

Here's my settings.
![image](https://user-images.githubusercontent.com/4055444/44443644-25e72300-a61c-11e8-8f8c-84ac90d0a000.png)

Running the cmd below opens gVim which means that vim.exe's location is in the environment path.
![image](https://user-images.githubusercontent.com/4055444/44443665-48793c00-a61c-11e8-860b-1bc7b0fc8032.png)

**Comment by jonsmithers** [comment]
Windows isn't currently supported, but I _would_ like to somehow support `gvim` and `integrated-terminal` on it. I'll see if I can fix this in the next couple days.

In the meantime I suspect you'd have better luck on Windows with [OpenVim](https://marketplace.visualstudio.com/items?itemName=mattn.OpenVim) because you can explicitly specify the path with the `openvim.executablePath` setting.

For my own future self-reference, [this stackoverflow post](https://stackoverflow.com/questions/37459717/error-spawn-enoent-on-windows) might reflect the issue described above. Maybe [cross-spawn](https://github.com/moxystudio/node-cross-spawn) would be helpful.

**Comment by jonsmithers** [comment]
This seems like something that would take a good chunk of hours to figure out, and I've unfortunately been keeping rather busy. For the meantime, I've added a more helpful message for people who try to use this plugin on windows.

**Comment by jonsmithers** [comment]
Thanks to  pull request https://github.com/jonsmithers/vscode-open-in-vim/pull/6, there is Windows support for vim in the integrated terminal.
