### ISSUE TITLE
Set terminal executable on linux

### ISSUE THREAD

**Issue by Feresey** [jonsmithers/vscode-open-in-vim#7]
It seems to me that leaving the choice of only two terminals (gnome & tilix) is wrong.
Please, add option `"open-in-vim.terminalExecutable"`.

**Comment by jonsmithers** [comment]
I think the difficulty with this is that most terminals have different ways accepting a "run this command" argument. Here's how to launch plain vim in a couple different terminals that I know of:

```bash
tilix --command=vim
gnome-terminal --command=vim
alacritty --command=vim ( OR ) alacritty -e vim
xterm -e vim
kitty vim
```

There isn't much uniformity. When this extension launches a terminal, it has to know how pass the "run this command" argument to open vim to the right file and line number. And sadly, that varies across terminals.

**Comment by Feresey** [comment]
It means that user should specify the path to the terminal and arguments transferred for it.

**Comment by jonsmithers** [comment]
I do think we are beyond the scope of this extension, because we're launching an arbitrary program with arbitrary arguments.

It might be possible to put together a DIY solution for a given terminal using something like [External Tools](https://marketplace.visualstudio.com/items?itemName=lihui.vs-external-tools). As an example, I've gotten vscode to open the current file in gvim using the following _settings.json_ config:
```
    "vs-external-tools.externalCommand1.command": "gvim",
    "vs-external-tools.externalCommand1.cwd": "$(ProjectDir)",
    "vs-external-tools.externalCommand1.args": ["$(ItemPath)", "+call cursor($(CurLine), $(CurCol))"]
```

To open current file and line number in alacritty:

```
    "vs-external-tools.externalCommand2.command": "alacritty",
    "vs-external-tools.externalCommand2.cwd": "$(ProjectDir)",
    "vs-external-tools.externalCommand2.args": ["-e", "vim", "$(ItemPath)", "+call cursor($(CurLine), $(CurCol))"]
```

This would also work for xterm and kitty.

**Comment by Feresey** [comment]
Yes, thanks, this is exactly what I was looking for

**Comment by jonsmithers** [comment]
(Also, FWIW, if you want vscode to jump to the position you were in vim when you exited vim, this is another argument you can add): 

`"+autocmd VimLeavePre * execute '!code --goto ' . expand('%') . ':' . line('.') . ':' . col('.')"`

**Comment by Feresey** [comment]
Wow, thanks!
